/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package caiaja.janelas;

import caiaja.model.Aeroporto;
import caiaja.ontologia.acoes.PlanoDeVoo;
import java.util.ArrayList;
import java.util.List;
import javax.swing.event.ListDataListener;

/**
 *
 * @author fosa
 * Painel com o itinerário de voo do Piloto
 */
public class PlanoDeVooJPanel extends javax.swing.JPanel {

    AeroportosComboboxModel aeroportos;

    PlanoDeVoo planodevoo;

    /**
     * Creates new form PlanoDeVooJPanel
     *
     * @param planodevoo palno de voo a ser alterado
     * @param lista_aeroportos lista de aeroportos existenes no ambiente
     */
    public PlanoDeVooJPanel(PlanoDeVoo planodevoo, List<Aeroporto> lista_aeroportos) {
        this.planodevoo = planodevoo;

        this.aeroportos = new AeroportosComboboxModel(lista_aeroportos);
        if (lista_aeroportos.size() > 0) {
            planodevoo.setAeroportoDestino(lista_aeroportos.get(0));
            this.aeroportos.setSelectedItem(0);
        }
        initComponents();

    }

    @Override
    public void setVisible(boolean aFlag) {
        planodevoo.setAeroportoDestino((Aeroporto) aeroportos.getSelectedItem());
        super.setVisible(aFlag); //To change body of generated methods, choose Tools | Templates.
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        AeroportoOrigemNomeLabel = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jComboBox2 = new javax.swing.JComboBox();
        AviaoPrefixoLabel = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        PilotoNomeLabel = new javax.swing.JLabel();

        AeroportoOrigemNomeLabel.setText(planodevoo.getAeroportoOrigem().getNome());

        jLabel1.setText("Aeroporto de Origem");

        jLabel2.setText("Aeroporto Destino");

        jComboBox2.setModel(aeroportos);
        jComboBox2.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                jComboBox2FocusLost(evt);
            }
        });
        jComboBox2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jComboBox2MouseClicked(evt);
            }
        });
        jComboBox2.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jComboBox2KeyReleased(evt);
            }
        });

        AviaoPrefixoLabel.setText(planodevoo.getAviao().getPrefixo());

        jLabel3.setText("Aviao");

        jLabel4.setText("Piloto");

        PilotoNomeLabel.setText(planodevoo.getPiloto().getNome());

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel4)
                    .addComponent(jLabel3)
                    .addComponent(jLabel1)
                    .addComponent(jLabel2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jComboBox2, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(AviaoPrefixoLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(PilotoNomeLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(AeroportoOrigemNomeLabel, javax.swing.GroupLayout.DEFAULT_SIZE, 269, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(AeroportoOrigemNomeLabel))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jComboBox2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(AviaoPrefixoLabel))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(PilotoNomeLabel))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void jComboBox2FocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jComboBox2FocusLost
        planodevoo.setAeroportoDestino((Aeroporto) aeroportos.getSelectedItem());
//        System.err.println("Focus lost");
    }//GEN-LAST:event_jComboBox2FocusLost

    private void jComboBox2KeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jComboBox2KeyReleased
        planodevoo.setAeroportoDestino((Aeroporto) aeroportos.getSelectedItem());
//        System.err.println("key released");
    }//GEN-LAST:event_jComboBox2KeyReleased

    private void jComboBox2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jComboBox2MouseClicked
        planodevoo.setAeroportoDestino((Aeroporto) aeroportos.getSelectedItem());
//        System.err.println("mouse clicked");
    }//GEN-LAST:event_jComboBox2MouseClicked


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel AeroportoOrigemNomeLabel;
    private javax.swing.JLabel AviaoPrefixoLabel;
    private javax.swing.JLabel PilotoNomeLabel;
    private javax.swing.JComboBox jComboBox2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    // End of variables declaration//GEN-END:variables

    public PlanoDeVoo getPlanodevoo() {
        return planodevoo;
    }

    public void setPlanodevoo(PlanoDeVoo planodevoo) {
        this.planodevoo = planodevoo;
    }

    public AeroportosComboboxModel getAeroportos() {
        return aeroportos;
    }

    public void setAeroportos(AeroportosComboboxModel aeroportos) {
        this.aeroportos = aeroportos;
    }

    private class AeroportosComboboxModel implements javax.swing.ComboBoxModel {

        List<ListDataListener> listeners;
        List<Aeroporto> aeroportos;
        int selecionado;

        public AeroportosComboboxModel() {
            selecionado = 0;
            listeners = new ArrayList<>();
            aeroportos = new ArrayList<>();
        }

        public AeroportosComboboxModel(List<Aeroporto> aeroportos) {
            selecionado = 0;
            listeners = new ArrayList<>();
            this.aeroportos = aeroportos;
        }

        @Override
        public void setSelectedItem(Object anItem) {
            if (anItem.getClass() == Aeroporto.class) {
                selecionado = aeroportos.indexOf(anItem);
            }
        }

        @Override
        public Object getSelectedItem() {
            if (selecionado >= aeroportos.size()) {
                return null;
            }
            return aeroportos.get(selecionado);
        }

        @Override
        public int getSize() {
            return aeroportos.size();
        }

        @Override
        public Object getElementAt(int index) {
            return aeroportos.get(index);
        }

        @Override
        public void addListDataListener(ListDataListener l) {
            listeners.add(l);
        }

        @Override
        public void removeListDataListener(ListDataListener l) {
            listeners.remove(l);
        }

    }
}
